global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'djangoapp'
    static_configs:
      - targets: ['djangoapp:80']
    metrics_path: /metrics
    scheme: http

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    metrics_path: /metrics
    scheme: http
